name: Deploy to Octopus

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Octopus CLI
        run: |
          curl -L https://github.com/OctopusDeploy/cli/releases/download/v2.4.0/octopus_2.4.0_linux_amd64.tar.gz | tar xz


      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: application-package

      - name: Push Package to Octopus
        run: octo push --server ${{ secrets.OCTOPUS_SERVER }} --apiKey ${{ secrets.OCTOPUS_API_KEY }} --package application-package.jar --space "Default"

      - name: Create Release in Octopus
        run: |
          octo create-release --server ${{ secrets.OCTOPUS_SERVER }} --apiKey ${{ secrets.OCTOPUS_API_KEY }} --project "Demo" --deployTo "Development" --version 1.0.0 --packageversion 1.0.0
